### ISSUE TITLE
Not working with chai-as-promised

### ISSUE THREAD

**Issue by rickwargo** [onechiporenko/chai-string#9]
I am unable to get the following code to work with chai-as-promised. 

```javascript
describe('the complete help intent', function () {
    it('should respond with the complete help message', function () {
        var result = request.intentRequest({ name: 'CompleteHelpIntent' });
        return result.should.eventually.startWith('<speak>' + Text.helpMessage);
    });
});
```

The above code responds with the following, I believe because the str parameter in `chai.string.startsWith` is a `Promise` and not a string.
```
TypeError: undefined is not a function
    at Object.chai.string.startsWith (/Users/rick/Code/Alexa/alexa-app/node_modules/chai-string/chai-string.js:23:16)
    at startsWithMethodWrapper (/Users/rick/Code/Alexa/alexa-app/node_modules/chai-string/chai-string.js:81:19)
    at assert (node_modules/chai/lib/chai/utils/addChainableMethod.js:83:49)
    at Context.<anonymous> (test/intents.js:57:41)
```

I need to revert to an async pattern for the test to be successful.

```javascript
describe('the help intent', function () {
    it('should respond with the help message', function () {
        return request.intentRequest({ name: 'AMAZON.HelpIntent' })
            .then(function (result) {
                result.should.startWith('<speak>' + Text.helpMessage);
            });
    });
});
```

**Comment by onechiporenko** [comment]
According to https://github.com/domenic/chai-as-promised/blob/f1b7db7aea36eb60d3beac69999854d55fafcf81/lib/chai-as-promised.js#L344-L370, which plugin-order do you have?
Please, try to `chai.use('chai-string')` before `chai.use('chai-as-promised')`.

**Comment by rickwargo** [comment]
Thank you! Indeed the order is significant with .use(). The following code resolved the issue:

```javascript
var chai = require('chai'),
    chaiAsPromised = require('chai-as-promised'),
    chaiString = require('chai-string'),
    should = require('chai').should();

chai.use(chaiString);
chai.use(chaiAsPromised);
```

**Comment by rickwargo** [comment]
After adding more test files, it took me quite a while to realize that order is important across the files. Ensure the first test file mocha executes has the order correct.
